name: test-api
version: '0.1'
summary: Greets the user of the API
description: Greeter

grade: devel
confinement: devmode
base: core22

apps:
  test-api:
    command: bin/test-api

parts:
  test-api:
    source: .
    plugin: npm
    build-snaps: [node/16/stable]

architectures:
  - build-on: arm64
  - build-on: amd64
    