name: test-api
version: '0.1'
summary: Greets the user of the API!
description: Greeter

grade: devel
confinement: devmode
base: core20

apps:
  test-api:
    command: bin/test-api

parts:
  test-api:
    source: .
    plugin: npm
    npm-node-version: 14.16.1

architectures:
  - build-on: amd64
  - build-on: armhf
    
